version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - '6379:6379'
  web:
    build: .
    command: bash -c 'python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - redis
    depends_on:
      - db
      - redis

  celery:
    build: .
    volumes:
      - .:/code
    container_name: celery_worker
    command: bash -c 'celery -A djangonews worker -l info'
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=news_db
      - POSTGRES_USER=news_user
      - POSTGRES_PASSWORD=qwe123

volumes:
  postgres_data:
